require('dotenv').config();
const express = require('express');
const cors = require('cors');
const connectDB = require('./config/db');
const authRoutes = require('./routes/authRoutes');
const bedRoutes = require('./routes/bedRoutes');
const staffRoutes = require('./routes/staffRoutes');
const appointmentRoutes = require('./routes/appointmentRoutes');
const dashboardRoutes = require('./routes/dashboardRoutes');
const patientRoutes = require('./routes/patientRoutes');
const app = express();
app.use(cors());
app.use(express.json());
connectDB();
app.get('/', (req, res) => {
  res.json({ message: 'SIH Hospital Resource Optimization API is running' });
});
app.use('/api/auth', authRoutes);
app.use('/api/beds', bedRoutes);
app.use('/api/staff', staffRoutes);
app.use('/api/appointments', appointmentRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/patients', patientRoutes);
const PORT = process.env.PORT || 5000;
app.listen(PORT, "127.0.0.1", () => console.log(`Server running on port ${PORT}`));
